server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/bibliotheque
spring.datasource.username=bibliotheque
spring.datasource.password=bibliotheque

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# Le code (conçu pour Spring Boot 2.4) utilise des références circulaires
# (jwtRequestFilter -> JwtService -> WebSecurityConfiguration -> jwtRequestFilter)
spring.main.allow-circular-references=true
